language: cpp

addons:
  apt:
    packages:
      - cmake
      - libusb-1.0-0-dev
  homebrew:
    packages:
      - cmake
os:
  - linux
    dist: xenial
  - osx

script:
  - mkdir build && cd build
  - cmake ..
  - make
